/**
 * Parser coverage measurement.
 *
 * A naive "did it parse?" metric is worthless here: the parser is deliberately
 * total, folding anything it doesn't recognize into a free-text `condition`, so
 * that metric reads 100% no matter how badly the grammar is doing. These three
 * measures can each actually fail:
 *
 *   1. RECALL — every university course code present in the clause text must
 *      appear somewhere in the AST. A dropped code is a silent missing edge and
 *      is the only unambiguous correctness bug the parser can have.
 *   2. FREE TEXT — the share of each clause's characters that ended up inside
 *      `condition`/`unparsed` nodes. Falling means the grammar understands more.
 *   3. UNCLASSIFIED — `condition` nodes we couldn't even categorize, ranked by
 *      frequency, which is the to-do list for the next grammar pass.
 */
import type { RequirementNode } from '../../src/lib/types.ts';
import { collectCourseCodes } from './parseRequirement.ts';
import { extractCourseCodes } from './normalizeCode.ts';

export interface ClauseSample {
	course: string;
	kind: 'prerequisite' | 'corequisite';
	text: string;
	ast: RequirementNode | null;
}

export interface CoverageReport {
	clauses: number;
	/** Clauses where the AST dropped a course code that the raw text mentions. */
	missingCodes: { course: string; text: string; missing: string[] }[];
	freeTextRatio: number;
	unparsedClauses: number;
	unclassified: { raw: string; count: number }[];
	conditionTypes: Record<string, number>;
}

/** Characters of the clause that landed in free-text nodes, plus condition tallies. */
function walkFreeText(
	node: RequirementNode | null,
	onCondition: (type: string, raw: string) => void
): number {
	if (!node) return 0;

	switch (node.kind) {
		case 'condition':
			onCondition(node.conditionType, node.raw);
			return node.raw.length;
		case 'unparsed':
			onCondition('unparsed', node.raw);
			return node.raw.length;
		case 'withGrade':
			return walkFreeText(node.child, onCondition);
		case 'all':
		case 'oneOf':
		case 'nOf':
			return node.children.reduce((sum, child) => sum + walkFreeText(child, onCondition), 0);
		default:
			return 0;
	}
}

function hasUnparsedNode(node: RequirementNode | null): boolean {
	if (!node) return false;
	switch (node.kind) {
		case 'unparsed':
			return true;
		case 'withGrade':
			return hasUnparsedNode(node.child);
		case 'all':
		case 'oneOf':
		case 'nOf':
			return node.children.some(hasUnparsedNode);
		default:
			return false;
	}
}

export function buildCoverage(samples: ClauseSample[]): CoverageReport {
	const missingCodes: CoverageReport['missingCodes'] = [];
	const unclassified = new Map<string, number>();
	const conditionTypes: Record<string, number> = {};
	let freeTextChars = 0;
	let totalChars = 0;
	let unparsedClauses = 0;

	for (const sample of samples) {
		const expected = extractCourseCodes(sample.text);
		const actual = new Set(collectCourseCodes(sample.ast));
		const missing = expected.filter((code) => !actual.has(code));
		if (missing.length) missingCodes.push({ course: sample.course, text: sample.text, missing });

		totalChars += sample.text.length;
		freeTextChars += walkFreeText(sample.ast, (type, raw) => {
			conditionTypes[type] = (conditionTypes[type] ?? 0) + 1;
			if (type === 'other' || type === 'unparsed') {
				unclassified.set(raw, (unclassified.get(raw) ?? 0) + 1);
			}
		});

		if (hasUnparsedNode(sample.ast)) unparsedClauses++;
	}

	return {
		clauses: samples.length,
		missingCodes,
		freeTextRatio: totalChars === 0 ? 0 : freeTextChars / totalChars,
		unparsedClauses,
		unclassified: [...unclassified.entries()]
			.map(([raw, count]) => ({ raw, count }))
			.sort((a, b) => b.count - a.count || b.raw.length - a.raw.length),
		conditionTypes
	};
}

export function formatCoverage(report: CoverageReport, fetchedAt: string): string {
	const pct = (value: number) => `${(value * 100).toFixed(1)}%`;
	const lines: string[] = [
		'# Prerequisite parser coverage',
		'',
		`Snapshot fetched ${fetchedAt}. Regenerated by \`bun run build:data\`.`,
		'',
		'| Metric | Value |',
		'| --- | --- |',
		`| Requirement clauses | ${report.clauses} |`,
		`| Clauses dropping a course code | ${report.missingCodes.length} |`,
		`| Clause text that is free text | ${pct(report.freeTextRatio)} |`,
		`| Clauses with an unparsed span | ${report.unparsedClauses} |`,
		'',
		'## Condition nodes by type',
		'',
		...Object.entries(report.conditionTypes)
			.sort((a, b) => b[1] - a[1])
			.map(([type, count]) => `- \`${type}\`: ${count}`),
		''
	];

	if (report.missingCodes.length) {
		lines.push(
			'## Dropped course codes (correctness bugs — fix these first)',
			'',
			...report.missingCodes
				.slice(0, 50)
				.map(
					(entry) =>
						`- **${entry.course}** missing \`${entry.missing.join(', ')}\` in: ${entry.text}`
				),
			''
		);
	}

	lines.push(
		'## Unclassified free text, by frequency',
		'',
		'The next grammar improvement should come from the top of this list.',
		'',
		...report.unclassified.slice(0, 60).map((entry) => `- ${entry.count}× \`${entry.raw}\``),
		''
	);

	return lines.join('\n');
}
